# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_choose_dialog(object):
    def setupUi(self, choose_dialog):
        choose_dialog.setObjectName("choose_dialog")
        choose_dialog.resize(327, 93)
        self.verticalLayout = QtWidgets.QVBoxLayout(choose_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.choose_label = QtWidgets.QLabel(choose_dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.choose_label.setFont(font)
        self.choose_label.setObjectName("choose_label")
        self.horizontalLayout.addWidget(self.choose_label)
        self.choose_cb = QtWidgets.QComboBox(choose_dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.choose_cb.setFont(font)
        self.choose_cb.setObjectName("choose_cb")
        self.horizontalLayout.addWidget(self.choose_cb)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(choose_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(choose_dialog)
        self.buttonBox.accepted.connect(choose_dialog.accept)
        self.buttonBox.rejected.connect(choose_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(choose_dialog)

    def retranslateUi(self, choose_dialog):
        _translate = QtCore.QCoreApplication.translate
        choose_dialog.setWindowTitle(_translate("choose_dialog", "Выбор"))
        self.choose_label.setText(_translate("choose_dialog", "Выберите"))
