# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_confirm(object):
    def setupUi(self, confirm):
        confirm.setObjectName("confirm")
        confirm.resize(336, 134)
        self.verticalLayout = QtWidgets.QVBoxLayout(confirm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(confirm)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.new_timetable = QtWidgets.QRadioButton(confirm)
        self.new_timetable.setObjectName("new_timetable")
        self.verticalLayout.addWidget(self.new_timetable)
        self.old_timetable = QtWidgets.QRadioButton(confirm)
        self.old_timetable.setObjectName("old_timetable")
        self.verticalLayout.addWidget(self.old_timetable)
        self.buttonBox = QtWidgets.QDialogButtonBox(confirm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(confirm)
        self.buttonBox.accepted.connect(confirm.accept)
        self.buttonBox.rejected.connect(confirm.reject)
        QtCore.QMetaObject.connectSlotsByName(confirm)

    def retranslateUi(self, confirm):
        _translate = QtCore.QCoreApplication.translate
        confirm.setWindowTitle(_translate("confirm", "Подтвердите действие"))
        self.label.setText(_translate("confirm", "Обнаружен готовый табель"))
        self.new_timetable.setText(_translate("confirm", "Удалить данные и сформировать табель заново"))
        self.old_timetable.setText(_translate("confirm", "Открыть готовый табель"))
