# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'directory.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_directory(object):
    def setupUi(self, directory):
        directory.setObjectName("directory")
        directory.resize(997, 526)
        self.verticalLayout = QtWidgets.QVBoxLayout(directory)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.category_rb = QtWidgets.QRadioButton(directory)
        self.category_rb.setObjectName("category_rb")
        self.horizontalLayout_2.addWidget(self.category_rb)
        self.position_rb = QtWidgets.QRadioButton(directory)
        self.position_rb.setObjectName("position_rb")
        self.horizontalLayout_2.addWidget(self.position_rb)
        self.profession_rb = QtWidgets.QRadioButton(directory)
        self.profession_rb.setObjectName("profession_rb")
        self.horizontalLayout_2.addWidget(self.profession_rb)
        self.vacation_type_rb = QtWidgets.QRadioButton(directory)
        self.vacation_type_rb.setObjectName("vacation_type_rb")
        self.horizontalLayout_2.addWidget(self.vacation_type_rb)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(directory)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.full_value_edit = QtWidgets.QLineEdit(directory)
        self.full_value_edit.setEnabled(False)
        self.full_value_edit.setObjectName("full_value_edit")
        self.horizontalLayout.addWidget(self.full_value_edit)
        self.label_2 = QtWidgets.QLabel(directory)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.short_name_edit = QtWidgets.QLineEdit(directory)
        self.short_name_edit.setEnabled(False)
        self.short_name_edit.setObjectName("short_name_edit")
        self.horizontalLayout.addWidget(self.short_name_edit)
        self.add_button = QtWidgets.QPushButton(directory)
        self.add_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pics/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_button.setIcon(icon)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout.addWidget(self.add_button)
        self.edit_button = QtWidgets.QPushButton(directory)
        self.edit_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("pics/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_button.setIcon(icon1)
        self.edit_button.setObjectName("edit_button")
        self.horizontalLayout.addWidget(self.edit_button)
        self.save_button = QtWidgets.QPushButton(directory)
        self.save_button.setEnabled(False)
        self.save_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("pics/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_button.setIcon(icon2)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.content_table = QtWidgets.QListView(directory)
        self.content_table.setObjectName("content_table")
        self.verticalLayout.addWidget(self.content_table)
        self.buttonBox = QtWidgets.QDialogButtonBox(directory)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(directory)
        self.buttonBox.accepted.connect(directory.accept)
        self.buttonBox.rejected.connect(directory.reject)
        QtCore.QMetaObject.connectSlotsByName(directory)

    def retranslateUi(self, directory):
        _translate = QtCore.QCoreApplication.translate
        directory.setWindowTitle(_translate("directory", "Справочник"))
        self.category_rb.setText(_translate("directory", "Категории"))
        self.position_rb.setText(_translate("directory", "Должности"))
        self.profession_rb.setText(_translate("directory", "Профессии"))
        self.vacation_type_rb.setText(_translate("directory", "Виды отпусков"))
        self.label.setText(_translate("directory", "Название полное"))
        self.label_2.setText(_translate("directory", "Краткое"))
