# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'replacement.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Replacement_form(object):
    def setupUi(self, Replacement_form):
        Replacement_form.setObjectName("Replacement_form")
        Replacement_form.resize(424, 340)
        self.verticalLayout = QtWidgets.QVBoxLayout(Replacement_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Replacement_form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.substitute = QtWidgets.QComboBox(Replacement_form)
        self.substitute.setObjectName("substitute")
        self.horizontalLayout.addWidget(self.substitute)
        self.label_2 = QtWidgets.QLabel(Replacement_form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.replaced = QtWidgets.QComboBox(Replacement_form)
        self.replaced.setObjectName("replaced")
        self.horizontalLayout.addWidget(self.replaced)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Replacement_form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.date_repl = QtWidgets.QDateEdit(Replacement_form)
        self.date_repl.setObjectName("date_repl")
        self.horizontalLayout_2.addWidget(self.date_repl)
        self.label_4 = QtWidgets.QLabel(Replacement_form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.hours = QtWidgets.QSpinBox(Replacement_form)
        self.hours.setObjectName("hours")
        self.horizontalLayout_2.addWidget(self.hours)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.add_button = QtWidgets.QPushButton(Replacement_form)
        self.add_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pics/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_button.setIcon(icon)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout_2.addWidget(self.add_button)
        self.edit_button = QtWidgets.QPushButton(Replacement_form)
        self.edit_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("pics/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_button.setIcon(icon1)
        self.edit_button.setObjectName("edit_button")
        self.horizontalLayout_2.addWidget(self.edit_button)
        self.save_button = QtWidgets.QPushButton(Replacement_form)
        self.save_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("pics/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_button.setIcon(icon2)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_2.addWidget(self.save_button)
        self.del_button = QtWidgets.QPushButton(Replacement_form)
        self.del_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("pics/del.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.del_button.setIcon(icon3)
        self.del_button.setObjectName("del_button")
        self.horizontalLayout_2.addWidget(self.del_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.replacements = QtWidgets.QTableView(Replacement_form)
        self.replacements.setObjectName("replacements")
        self.verticalLayout.addWidget(self.replacements)

        self.retranslateUi(Replacement_form)
        QtCore.QMetaObject.connectSlotsByName(Replacement_form)

    def retranslateUi(self, Replacement_form):
        _translate = QtCore.QCoreApplication.translate
        Replacement_form.setWindowTitle(_translate("Replacement_form", "Замены"))
        self.label.setText(_translate("Replacement_form", "Кто заменял"))
        self.label_2.setText(_translate("Replacement_form", "Кого заменял"))
        self.label_3.setText(_translate("Replacement_form", "Дата"))
        self.label_4.setText(_translate("Replacement_form", "Количество часов"))
