# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sicklist_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sicklist_edit(object):
    def setupUi(self, sicklist_edit):
        sicklist_edit.setObjectName("sicklist_edit")
        sicklist_edit.resize(310, 362)
        self.verticalLayout = QtWidgets.QVBoxLayout(sicklist_edit)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(sicklist_edit)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.teacher_cb = QtWidgets.QComboBox(sicklist_edit)
        self.teacher_cb.setObjectName("teacher_cb")
        self.horizontalLayout_2.addWidget(self.teacher_cb)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(sicklist_edit)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.date_begin = QtWidgets.QDateEdit(sicklist_edit)
        self.date_begin.setEnabled(False)
        self.date_begin.setObjectName("date_begin")
        self.horizontalLayout.addWidget(self.date_begin)
        self.label_3 = QtWidgets.QLabel(sicklist_edit)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.date_end = QtWidgets.QDateEdit(sicklist_edit)
        self.date_end.setEnabled(False)
        self.date_end.setObjectName("date_end")
        self.horizontalLayout.addWidget(self.date_end)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.sicklist = QtWidgets.QListView(sicklist_edit)
        self.sicklist.setObjectName("sicklist")
        self.verticalLayout.addWidget(self.sicklist)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.add_button = QtWidgets.QPushButton(sicklist_edit)
        self.add_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pics/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_button.setIcon(icon)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout_3.addWidget(self.add_button)
        self.edit_button = QtWidgets.QPushButton(sicklist_edit)
        self.edit_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("pics/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_button.setIcon(icon1)
        self.edit_button.setObjectName("edit_button")
        self.horizontalLayout_3.addWidget(self.edit_button)
        self.save_button = QtWidgets.QPushButton(sicklist_edit)
        self.save_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("pics/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_button.setIcon(icon2)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_3.addWidget(self.save_button)
        self.del_button = QtWidgets.QPushButton(sicklist_edit)
        self.del_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("pics/del.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.del_button.setIcon(icon3)
        self.del_button.setObjectName("del_button")
        self.horizontalLayout_3.addWidget(self.del_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(sicklist_edit)
        QtCore.QMetaObject.connectSlotsByName(sicklist_edit)

    def retranslateUi(self, sicklist_edit):
        _translate = QtCore.QCoreApplication.translate
        sicklist_edit.setWindowTitle(_translate("sicklist_edit", "Больничные"))
        self.label.setText(_translate("sicklist_edit", "Выберите учителя"))
        self.label_2.setText(_translate("sicklist_edit", "Начало"))
        self.label_3.setText(_translate("sicklist_edit", "Окончание"))
