# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teacherworkload.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_teacher_workload(object):
    def setupUi(self, teacher_workload):
        teacher_workload.setObjectName("teacher_workload")
        teacher_workload.resize(232, 229)
        self.verticalLayout = QtWidgets.QVBoxLayout(teacher_workload)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.teacher_label = QtWidgets.QLabel(teacher_workload)
        self.teacher_label.setObjectName("teacher_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.teacher_label)
        self.teacher_name = QtWidgets.QLineEdit(teacher_workload)
        self.teacher_name.setEnabled(False)
        self.teacher_name.setObjectName("teacher_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.teacher_name)
        self.label = QtWidgets.QLabel(teacher_workload)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.d1 = QtWidgets.QSpinBox(teacher_workload)
        self.d1.setObjectName("d1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.d1)
        self.label_2 = QtWidgets.QLabel(teacher_workload)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.d2 = QtWidgets.QSpinBox(teacher_workload)
        self.d2.setObjectName("d2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.d2)
        self.label_3 = QtWidgets.QLabel(teacher_workload)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.d3 = QtWidgets.QSpinBox(teacher_workload)
        self.d3.setObjectName("d3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.d3)
        self.label_4 = QtWidgets.QLabel(teacher_workload)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.d4 = QtWidgets.QSpinBox(teacher_workload)
        self.d4.setObjectName("d4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.d4)
        self.label_5 = QtWidgets.QLabel(teacher_workload)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.d5 = QtWidgets.QSpinBox(teacher_workload)
        self.d5.setObjectName("d5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.d5)
        self.label_6 = QtWidgets.QLabel(teacher_workload)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.total = QtWidgets.QLabel(teacher_workload)
        self.total.setObjectName("total")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.total)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(teacher_workload)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(teacher_workload)
        self.buttonBox.accepted.connect(teacher_workload.accept)
        self.buttonBox.rejected.connect(teacher_workload.reject)
        QtCore.QMetaObject.connectSlotsByName(teacher_workload)

    def retranslateUi(self, teacher_workload):
        _translate = QtCore.QCoreApplication.translate
        teacher_workload.setWindowTitle(_translate("teacher_workload", "Нагрузка по дням"))
        self.teacher_label.setText(_translate("teacher_workload", "Учитель:"))
        self.label.setText(_translate("teacher_workload", "Пн"))
        self.label_2.setText(_translate("teacher_workload", "Вт"))
        self.label_3.setText(_translate("teacher_workload", "Ср"))
        self.label_4.setText(_translate("teacher_workload", "Чт"))
        self.label_5.setText(_translate("teacher_workload", "Пт"))
        self.label_6.setText(_translate("teacher_workload", "Всего"))
        self.total.setText(_translate("teacher_workload", "0"))
